services:
  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"               # alloy UI
    environment:
      - GRAFANA_CLOUD_OTLP_USER     # from .env
      - GRAFANA_CLOUD_OTLP_TOKEN    # from .env
      - GRAFANA_CLOUD_OTLP_ENDPOINT # from .env
      - GRAFANA_CLOUD_PYROSCOPE_SERVER_ADDRESS  # from .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      # Stability level "public-preview" is needed to use pyroscope.receive_http at time of writing
      # https://grafana.com/docs/pyroscope/latest/configure-client/grafana-alloy/receive_profiles/
      - --stability.level=public-preview
      - /etc/alloy/config.alloy
    # Privileged mode needed to discover processes on host, also to use pyroscope.java and pyroscope.ebpf, bummers
    # (=> better to use sdk instrumentation in cases where that might be a problem)
    # https://github.com/grafana/pyroscope/blob/main/examples/grafana-alloy-auto-instrumentation/java/docker/docker-compose.yml#L20-L21
    # https://grafana.com/docs/pyroscope/latest/configure-client/grafana-alloy/java/#set-privileges-for-the-collector
    # https://grafana.com/docs/pyroscope/latest/configure-client/grafana-alloy/ebpf/configuration/#privileges
    privileged: true
    pid: host
  # Local pyroscope server for testing purposes
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - 4040:4040
  airlines:
    build:
      context: ./airlines
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=airlines
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=airlines,deployment.environment=local
      # Debug settings
      - OTEL_LOG_LEVEL=debug
      - OTEL_JAVAAGENT_DEBUG=true
      # Spring logging
      # - LOGGING_LEVEL_ROOT=DEBUG
  flights:
    build:
      context: ./flights
    ports:
      - "5001:5001"
    environment:
      - OTEL_SERVICE_NAME=flights
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=flights,deployment.environment=local
      # Debug settings
      - OTEL_LOG_LEVEL=debug
      - OTEL_PYTHON_LOG_LEVEL=debug
      # - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040  # test locally
      - PYROSCOPE_SERVER_ADDRESS=http://alloy:4041        # send to grafana cloud through alloy
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  alloy-data:
